service: chain-dreamers-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: img/{id}
          method: get

package:
  include:
    - eth-sdk/**
    - valise.json

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

custom:
  includeDependencies:
    enableCaching: true
