service: chain-dreamers-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 2048
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'staging'}
  region: ${opt:region, 'us-west-1'}
  environment:
    API_ASSETS_BUCKET_NAME: ${self:custom.s3.apiAssetsBucketName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:custom.s3.apiAssetsBucketName}/*"

functions:
  img:
    handler: handler.img
    events:
      - http:
          path: tokens/{id}/img
          method: get
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.id

  runnerToDreamer:
    handler: handler.runnerToDreamer
    events:
      - http:
          path: tokens/{id}/runnerToDreamer
          method: get

package:
  include:
    - eth-sdk/**
    - valise.json

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-apigw-binary
  - serverless-api-gateway-caching

custom:
  includeDependencies:
    enableCaching: true
  s3:
    apiAssetsBucketName: chain-dreamers-api-assets-${self:provider.stage}
  domainPath:
    test: 'test'
    staging: 'staging'
    prod: ''
  customDomain:
    domainName: api.chaindreamers.xyz
    basePath: ${self:custom.domainPath.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: false
  apiGatewayCaching:
    enabled: true
  apigwBinary:
    types:
      - 'image/png'
      - 'image/*'
      - '*/*'

resources:
  Resources:
    ApiAssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3.apiAssetsBucketName}
  Outputs:
    ApiAssetsBucketNameOutputKey:
      Value: !Ref ApiAssetsBucket

