[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../chain-dreamers-contracts"

[context.production]
  environment = { REACT_APP_CHAIN_ID = "1", REACT_APP_NETWORK = "mainnet", REACT_APP_RUNNERS_CONTRACT_ADDRESS = "0x97597002980134bea46250aa0510c9b90d87a587" }

[context.staging]
  environment = { REACT_APP_CHAIN_ID = "4", REACT_APP_NETWORK = "rinkeby" }
