version: 2.1
jobs:
  deploy-staging:
    docker:
      - image: cimg/python:3.10.2-node
    working_directory: ~/chain-dreamers-monorepo
    environment:
      NETWORK: rinkeby
    steps:
      - checkout
      - restore_cache:
          keys:
            - api-npm-deps-{{ checksum "~/chain-dreamers-monorepo/packages/chain-dreamers-api/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - api-npm-deps-
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            pip install dvc
            sudo npm i -g serverless
            cd ~/chain-dreamers-monorepo/packages/chain-dreamers-api && npm install
      - save_cache:
          paths:
            - node_modules
          key: api-npm-deps-{{ checksum "~/chain-dreamers-monorepo/packages/chain-dreamers-api/package-lock.json" }}
      - run:
          name: DVC pull
          command: AWS_ACCESS_KEY_ID=$DVC_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$DVC_AWS_SECRET_ACCESS_KEY cd ~/chain-dreamers-monorepo/packages/chain-dreamers-image-processing && dvc pull
      - run:
          name: Deploy application
          command: cd ~/chain-dreamers-monorepo/packages/chain-dreamers-api && npm run deploy:test

  deploy-prod:
    docker:
      - image: cimg/python:3.10.2-node
    working_directory: ~/chain-dreamers-monorepo
    environment:
      NETWORK: mainnet
    steps:
      - checkout
      - restore_cache:
          keys:
            - api-npm-deps-{{ checksum "~/chain-dreamers-monorepo/packages/chain-dreamers-api/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - api-npm-deps-
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            pip install dvc
            sudo npm i -g serverless
            cd ~/chain-dreamers-monorepo/packages/chain-dreamers-api && npm install
      - save_cache:
          paths:
            - node_modules
          key: api-npm-deps-{{ checksum "~/chain-dreamers-monorepo/packages/chain-dreamers-api/package-lock.json" }}
      - run:
          name: DVC pull
          command: AWS_ACCESS_KEY_ID=$DVC_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$DVC_AWS_SECRET_ACCESS_KEY cd ~/chain-dreamers-monorepo/packages/chain-dreamers-image-processing && dvc pull
      - run:
          name: Deploy application
          command: cd ~/chain-dreamers-monorepo/packages/chain-dreamers-api && npm run deploy:prod

workflows:
  deploy-workflow:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: test
      - deploy-prod:
          filters:
            branches:
              only: main
