version: 2.1
jobs:
  deploy-staging:
    docker:
      - image: cimg/node:17.4.0
    working_directory: ~/chain-dreamers-monorepo/packages/chain-dreamers-api
    environment:
      NETWORK: rinkeby
    steps:
      - checkout
      - restore_cache:
      keys:
        - npm-deps-{{ checksum "package-lock.json" }}
        # fallback to using the latest cache if no exact match is found
        - npm-deps-
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Deploy application
          command: npm run deploy:staging

  deploy-prod:
    docker:
      - image: cimg/node:17.4.0
    working_directory: ~/chain-dreamers-monorepo/packages/chain-dreamers-api
    environment:
      NETWORK: mainnet
    steps:
      - checkout
      - restore_cache:
      keys:
        - npm-deps-{{ checksum "package-lock.json" }}
        # fallback to using the latest cache if no exact match is found
        - npm-deps-
        - run:
            name: Install Serverless CLI and dependencies
            command: |
              sudo npm i -g serverless
              npm install
        - save_cache:
            paths:
              - node_modules
            key: npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Deploy application
          command: npm run deploy:prod

workflows:
  deploy-workflow:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: test
      - deploy-prod:
          filters:
            branches:
              only: main
